name: Lottery
plugins:
- name: solidity
- name: infura
- name: networks
- name: test

ethereum:
  default_network: sepolia
  mainnet: 
    default_provider: infura
  mainnet_fork:
    default_provider: foundry
  goerli:
    default_provider: infura
  sepolia:
    default_provider: infura
  local:
    default_provider: test

foundry:
  host: http://localhost:8545
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura

solidity: 
  import_remapping:
    - "@openzeppelin=OpenZeppelin/5.0.1"
    - "@chainlink=smartcontractkit/2.8.0"

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 5.0.1
  - name: smartcontractkit
    github: smartcontractkit/chainlink
    version: 2.8.0

deployments:
  ethereum:
    mainnet:
      - contract_type: AggregatorV3Interface
        address: "0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419"
      - contract_type: VRFV2WrapperInterface # this is for the direct funding method of Chainlink's VRF
        address: "0x5A861794B927983406fCE1D062e00b9368d97Df6"
      - contract_type: VRFCoordinator # this is for the subscription method of Chainlink's VRF
        address: "0x271682DEB8C4E0901D1a1550aD2e64D568E69909"
      - contract_type: LinkToken
        address: "0x514910771AF9Ca656af840dff83E8264EcF986CA"
    mainnet-fork:
      - contract_type: AggregatorV3Interface
        address: "0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419"
      - contract_type: VRFV2WrapperInterface
        address: "0x5A861794B927983406fCE1D062e00b9368d97Df6"
      - contract_type: VRFCoordinator
        address: "0x271682DEB8C4E0901D1a1550aD2e64D568E69909"
      - contract_type: LinkToken
        address: "0x514910771AF9Ca656af840dff83E8264EcF986CA"
    sepolia:
      - contract_type: AggregatorV3Interface
        address: "0x694AA1769357215DE4FAC081bf1f309aDC325306"
      - contract_type: VRFV2WrapperInterface
        address: "0xab18414CD93297B0d12ac29E63Ca20f515b3DB46" 
      - contract_type: VRFCoordinator 
        address: "0x8103B0A8A00be2DDC778e6e7eaa21791Cd364625"
      - contract_type: LinkToken
        address: "0x779877A7B0D9E8603169DdbD7836e478b4624789"
    
test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 5